version: 0.2

frontend:
  phases:
    install:
      runtime-versions:
        nodejs: 14
      commands:
        - npm install

    build:
      commands:
        - npm run build

  artifacts:
    files: '**/*'

  cache:
    paths:
      - node_modules/**/*


