version: 0.2

frontend:
  phases:
    build:
      commands: ["npm run build"]
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths: []


